Kuafor_web/Controllers/GirisController.cs
using Kuafor_web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authentication.Cookies;


namespace berber4.Controllers
{
    public class GirisController : Controller
    {
        public IActionResult GirisYap()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GirisYap(Kullanici k,string ReturnUrl)
        {
            BerberDbContext db = new BerberDbContext();
            var kullanici = db.Kullanicis.FirstOrDefault(kul => kul.Eposta == k.Eposta && MD5Sifrele( k.Parola) == kul.Parola && kul.Silindi == false && kul.Aktif == true);
           
            if(kullanici!=null)

            {

                string yetki = (bool)kullanici.Yetki ? "Yonetici" : "Uye" ;
                var talepler = new List<Claim>()
                {
                    new Claim(ClaimTypes.Email,kullanici.Eposta.ToString()),
                     new Claim(ClaimTypes.Role,yetki),
                     new Claim(ClaimTypes.NameIdentifier,kullanici.KullaniciId.ToString())

                };
                ClaimsIdentity kimlik= new ClaimsIdentity(talepler,"Login");
                ClaimsPrincipal kural = new ClaimsPrincipal(kimlik);
                await HttpContext.SignInAsync(kural);
                if(!string.IsNullOrEmpty(ReturnUrl))
                {
                    
              
                    return Redirect(ReturnUrl);

                }
                else
                {

                    if ((bool)kullanici.Yetki)
                    {
                        return Redirect("/Home/Anasayfa");

                    }
                    else
                    {
                        return Redirect("/Home/Anasayfa");
                    }










                   
                }

            }
            ViewData["ErrorMessage"] = "Kayıtlı kullanıcı bulunamadı bilgilerinizi kontrol ediniz !!!";
           return View();
            

        }

        public static string MD5Sifrele(string sifrelenecekMetin)
        {

            // MD5CryptoServiceProvider sınıfının bir örneğini oluşturduk.
            MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();
            //Parametre olarak gelen veriyi byte dizisine dönüştürdük.
            byte[] dizi = Encoding.UTF8.GetBytes(sifrelenecekMetin);
            //dizinin hash'ini hesaplattık.
            dizi = md5.ComputeHash(dizi);
            //Hashlenmiş verileri depolamak için StringBuilder nesnesi oluşturduk.
            StringBuilder sb = new StringBuilder();
            //Her byte'i dizi içerisinden alarak string türüne dönüştürdük.

            foreach (byte ba in dizi)
            {
                sb.Append(ba.ToString("x2").ToLower());
            }

            //hexadecimal(onaltılık) stringi geri döndürdük.
            return sb.ToString();
        }



      
        public async Task<IActionResult>   CikisYap()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Anasayfa", "Home");
        }










    }
}

Kuafor_web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace berber4.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Kuafor_web/Controllers/YonetimController.cs
 
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using Kuafor_web.Models;
using System.Runtime.ConstrainedExecution;

namespace berber4.Controllers
{
    [Authorize(Roles = "Yonetici")]
    public class YonetimController : Controller
    {

        BerberDbContext db = new BerberDbContext();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RandevuAl()
        {




            return View();
        }






        public IActionResult RandevuIptal()
        {
            return View();
        }







        public IActionResult Bilgilerim()



        {
 
            int kulId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var kullanici = db.Kullanicis.Find(kulId);
            kullanici.Parola = "";
            return View(kullanici);
        }
        public IActionResult BilgilerimiGuncelle(Kullanici kul)
        {
            var kullanici = db.Kullanicis.Where(s => s.Silindi == false && s.KullaniciId == kul.KullaniciId).FirstOrDefault();



            kullanici.KullaniciIsim = kul.KullaniciIsim;
            kullanici.Eposta = kul.Eposta;
            kullanici.Telefon = kul.Telefon;

            try
            {
                if (kul.Parola.Trim().Length != 0)
                {

                    kullanici.Parola = MD5Sifrele(kul.Parola.Trim());



                }


            }

            catch { }

            db.Kullanicis.Update(kullanici);
            db.SaveChanges();

            return RedirectToAction("Bilgilerim");
        }





        public IActionResult CikisYap()
        {
            return View();
        }





         




        public IActionResult Kullanicilar()
        {
            var kullanicilar = db.Kullanicis.Where(s => s.Silindi == false).OrderBy(s => s.Yetki).OrderBy(s => s.KullaniciIsim).ToList();
            return View(kullanicilar);
        }
        public IActionResult BerberGoster()
        {
            var berberler = db.Berbers.Where(s => s.Pasif == false).OrderBy(s => s.BerberIsim).ToList();
            return View(berberler);
        }
        public IActionResult SalonGoster()
        {
            var salonlar = db.Salons.ToList();
            return View(salonlar);
        }

        public IActionResult BerberGetir(int id)
        {
            var berber = db.Berbers.Where(s => s.Pasif == false && s.BerberId == id).FirstOrDefault();


            return View("BerberGuncelle", berber);
        }
        public IActionResult SalonGetir(int id)
        {
            var salon = db.Salons.Where(s => s.SalonId == id).FirstOrDefault();


            return View("SalonGuncelle", salon);
        }

        public IActionResult SalonGuncelle(Salon sal)

        {

            var salon = db.Salons.Where(s => s.SalonId == sal.SalonId).FirstOrDefault();





             
            salon.SalonId = sal.SalonId;
            salon.SalonAd = sal.SalonAd;




            db.Salons.Update(salon);
            db.SaveChanges();

            return RedirectToAction("SalonGoster");
        }
        public IActionResult BerberGuncelle(Berber ber)

        {

            if (!ModelState.IsValid)
            {
                // Model geçerli değilse hataları göster
                return View(ber);
            }
            var berber = db.Berbers.Where(s => s.Pasif == false && s.BerberId == ber.BerberId).FirstOrDefault();




            berber.Berberkazanc = ber.Berberkazanc;
            berber.Aktif = ber.Aktif;
            //   berber.SalonAd = ber.SalonAd;
            berber.SalonId = ber.SalonId;
            berber.IsBaslangicTarihi = ber.IsBaslangicTarihi;

            var salon_bul = db.Salons.Where(s => s.SalonId == berber.SalonId).FirstOrDefault();
            berber.CalisilmayanGun = ber.CalisilmayanGun;
            berber.SalonAd = salon_bul.SalonAd;
            berber.BerberId = ber.BerberId;
            berber.VerilenHizmetler = ber.VerilenHizmetler;
            berber.IsBitisSaati = ber.IsBitisSaati;
            berber.IsBaslangicSaati = ber.IsBaslangicSaati;




            db.Berbers.Update(berber);
            db.SaveChanges();

            return RedirectToAction("BerberGoster");
        }

        public IActionResult BerberSil(int id)

        {

            var berber = db.Berbers.Where(s => s.Pasif == false && s.BerberId == id).FirstOrDefault();




            berber.Pasif = true;
            // sayfa.Aktif = false;


            db.Berbers.Update(berber);
            db.SaveChanges();

            return RedirectToAction("BerberGoster");

        }
        public IActionResult SalonEkle() //httpget

        {



            return View();
        }
        [HttpPost]
        public IActionResult SalonEkle(Salon s)  

        {
            if (!ModelState.IsValid)
            {
                // Model geçerli değilse hataları göster
                return View(s);
            }

            db.Salons.Add(s);

            db.SaveChanges();


            return RedirectToAction("SalonGoster");
        }
        public IActionResult BerberEkle() 

        {



            return View();
        }




        [HttpPost]
        public IActionResult BerberEkle(Berber b)  

        {
            if (!ModelState.IsValid)
            {
                // Model geçerli değilse hataları göster
                return View(b);
            }
            // Model geçerli ise işlem yapılır
         
            if (ModelState.IsValid)
            {
                // Veritabanından SalonId'ye göre SalonAd'ı bul
                var salon = db.Salons.FirstOrDefault(s => s.SalonId == b.SalonId);
                if (salon != null)
                {
                    b.SalonAd = salon.SalonAd; // SalonAd'ı Berber nesnesine ata
                }

            }
            b.Berberkazanc = 0;
            b.Pasif = false;
            
            db.Berbers.Add(b);

            db.SaveChanges();


            return RedirectToAction("BerberGoster");
        }
        public IActionResult KullaniciEkle() //httpget

        {



            return View();
        }
        [HttpPost]
        public IActionResult KullaniciEkle(Kullanici k)  

        {
            if (!ModelState.IsValid)
            {
                // Model geçerli değilse hataları göster
                return View(k);
            }
            k.Silindi = false;
            k.Parola = MD5Sifrele(k.Parola.Trim());
            db.Kullanicis.Add(k);

            db.SaveChanges();


            return RedirectToAction("Kullanicilar");
        }



        public IActionResult KullaniciGetir(int id)

        {

            var kullanici = db.Kullanicis.Where(s => s.Silindi == false && s.KullaniciId == id).FirstOrDefault();


            return View("KullaniciGuncelle", kullanici);
        }


        public IActionResult KullaniciGuncelle(Kullanici kul)

        {

            var kullanici = db.Kullanicis.Where(s => s.Silindi == false && s.KullaniciId == kul.KullaniciId).FirstOrDefault();






            kullanici.Aktif = kul.Aktif;

            kullanici.KullaniciIsim = kul.KullaniciIsim;
            kullanici.Eposta = kul.Eposta;
            kullanici.Telefon = kul.Telefon;

            kullanici.Yetki = kul.Yetki;
            try
            {
                if (kul.Parola.Trim().Length != 0)
                {

                    kullanici.Parola = MD5Sifrele(kul.Parola.Trim());



                }


            }

            catch { }

            db.Kullanicis.Update(kullanici);
            db.SaveChanges();

            return RedirectToAction("Kullanicilar");
        }




        public IActionResult KullaniciSil(int id)
        {
            // Kullanıcının randevuları var mı kontrol et
            var randevuKontrol = db.Randevus.Where(k => k.KullaniciId == id).ToList();

            // Eğer randevu varsa, silinemez
            if (randevuKontrol.Any())
            {
                TempData["ErrorMessage"] = "Kullanıcının randevusu bulunduğundan silinemez";


                return RedirectToAction("Kullanicilar");
            }

            // Eğer randevu yoksa, kullanıcıyı sil
            var kullanici = db.Kullanicis.Where(s => s.Silindi == false && s.KullaniciId == id).FirstOrDefault();
            if (kullanici != null)
            {
                kullanici.Silindi = true; // Silindi bayrağını güncelle
                db.Kullanicis.Update(kullanici);
                db.SaveChanges();
            }

            return RedirectToAction("Kullanicilar");
        }



        public IActionResult SalonSil(int id)

        {

            var salon = db.Salons.Where(s => s.SalonId == id).FirstOrDefault();







            db.Salons.Remove(salon);
            db.SaveChanges();

            return RedirectToAction("SalonGoster");
        }
        public IActionResult RandevuOnay()

        {






            var Randevu = db.Randevus.Where(r => r.Aktif == true).OrderBy(r => r.RandevuOnay).ToList();
            //  var kulllanici=   db.Kullanicis.Where(k => k.KullaniciId == kullaniciId).FirstOrDefault();

            return View(Randevu);


        }



        public IActionResult Onay(int id)
        {


            var bulunanRandevu = db.Randevus.FirstOrDefault(m => m.RandevuId == id);
            bulunanRandevu.RandevuOnay = true;
            db.Randevus.Update(bulunanRandevu);
            db.SaveChanges(); // Değişiklikleri kaydet

            return RedirectToAction("RandevuOnay"); // Kullanıcıyı listeye geri yönlendir


        }
        public IActionResult RandevuSil(int id)
        {


            var bulunanRandevu = db.Randevus.FirstOrDefault(m => m.RandevuId == id);


            var berber= db.Berbers.FirstOrDefault(s => s.BerberId == bulunanRandevu.BerberId);

Kuafor_web/Views/Shared/User.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kullanıcı Paneli</title>
    <style>
        /* Genel Stil */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            background-color: #121212;
            color: #f1f1f1;
        }

        /* Sidebar */
        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #1e1e1e;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 20px 10px;
        }

            .sidebar h3 {
                color: #FF6600;
                text-align: center;
                font-size: 1.5em;
                margin-bottom: 30px;
            }

            .sidebar a {
                display: block;
                color: #f1f1f1;
                padding: 12px 20px;
                text-decoration: none;
                border-radius: 5px;
                margin-bottom: 10px;
                transition: background-color 0.3s ease, color 0.3s ease;
                font-weight: 500;
            }

                .sidebar a:hover {
                    background-color: #FF6600;
                    color: #121212;
                }

                .sidebar a.active {
                    background-color: #FF6600;
                    color: #121212;
                }

        /* Ana İçerik */
        .content {
            flex-grow: 1;
            padding: 20px;
        }

            .content h1 {
                color: #FF6600;
                font-size: 2em;
                margin-bottom: 20px;
            }

        /* Footer */
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #ddd;
        }
    </style>
</head>
<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <div>
            <h3>Kullanıcı Paneli</h3>
            <a asp-controller="Home" asp-action="RandevuGoster" class="active">Randevularım</a>
            <a asp-controller="Home" asp-action="Randevu">Randevu Al</a>
            <a asp-controller="Home" asp-action="RandevuGoster">Randevu İptal</a>
            <a asp-controller="Home" asp-action="Bilgilerim">Bilgilerim</a>
            <a asp-controller="Home" asp-action="Tavsiye">İmaj Tavsiyesi</a>
            <a asp-controller="Home" asp-action="AnaSayfa">Anasayfa</a>
        </div>
        <div>
            <a asp-controller="Giris" asp-action="CikisYap" style="color: #FF6666; font-weight: bold;">Çıkış Yap</a>
        </div>
    </div>

    <!-- Ana İçerik Alanı -->
    <div class="content">
        @RenderBody()
    </div>
</body>
</html>

Kuafor_web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - berber4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/berber4.styles.css" asp-append-version="true" />
    <style>
        button:focus {
            outline: 0;
        }

        .navbar .dropdown-menu .form-control {
            width: 200px;
        }

        /* Navbar arka planını siyah yapar */
        .navbar {
            background-color: black;
        }

            /* Navbar linklerinin rengini beyaz yapar */
            .navbar .nav-link {
                color: white;
            }

                /* Navbar linklerine hover efekti ekler */
                .navbar .nav-link:hover {
                    color: #f8f9fa;
                }
    </style>
    <style>
         
        .dropdown-menu {
            background-color: #343a40; 
            color: white;  
        }

            
            .dropdown-menu .dropdown-item:hover {
                background-color: #495057; 
                color: white;  
            }
    </style>

</head>
<body>
    <header>
        <!-- Navbar'ı siyah yapmak için navbar-dark bg-dark sınıflarını kullan -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @{

                            BerberDbContext db = new BerberDbContext();
                            var ustmenu = db.Menulers.Where(eleman => eleman.UstId == null && eleman.Silindi == false && eleman.Aktif == true).OrderBy(e => e.Sıra).ToList();
                            var salonlar = db.Salons.ToList();
                            foreach (var item in ustmenu)
                            {
                                var altmenu = db.Menulers.Where(eleman => eleman.UstId == item.MenuId && eleman.Silindi == false && eleman.Aktif == true).OrderBy(e => e.Sıra).ToList();

                                if (altmenu.Count == 0)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" href="@item.Url">@item.Baslık</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-action="Subeler" asp-controller="Home">
                                            Şubeler
                                        </a>
                                    </li>

                                }
                            }
                        }
                    </ul>

                    <ul class="nav navbar-nav flex-row justify-content-between ml-auto">

                        @{
                            @using System.Security.Claims;



                            int kulId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
                            var kullanici = db.Kullanicis.Where(k => k.KullaniciId == kulId).FirstOrDefault();
                            if (kullanici != null)
                            {

                                string kulAdi = kullanici.KullaniciIsim;
                                <li>
                                    <div class="form-group">
                                        <small>
                                            <span style="color: #e65100;">Hoşgeldin @kulAdi</span>
                                            <a href="/Giris/CikisYap" class="btn btn-danger btn-block text-dark" onclick="return confirm('Çıkış yapılsın mı?')">Çıkış</a>

                                        </small>

                                    </div>

                                </li>



                            }

                            ///////////////////////////

                            else//kulanıcı girisi yapılmamıs
                            {
                                <li class="nav-item dropdown order-1">
                                    <button type="button" id="dropdownMenu1" data-bs-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Giriş <span class="caret"></span></button>
                                    <ul class="dropdown-menu dropdown-menu-end mt-1">
                                        <li class="p-3">
                                            <form class="form" role="form" method="post" action="Giris/GirisYap">
                                                <div class="form-group">
                                                    <input id="Eposta" placeholder="E-posta" name="Eposta" class="form-control form-control-sm" type="E-posta" />
                                                </div>
                                                <div class="form-group">
                                                    <input id="Parola" placeholder="Parola" name="Parola" class="form-control form-control-sm" type="password" />
                                                </div>
                                                <div class="form-group">
                                                    <button type="submit" asp-action="GirisYap" asp-controller="Giris" class="btn btn-primary btn-block">Giriş</button>

                                                </div>
                                                <div class="form-group  text-center" method="post">

                                                    <small><a asp-action="Kaydol" asp-controller="Home" o>Kaydol</a></small>
                                                </div>
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            }

                        }
                        <!-- İşlemler Butonu -->
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form action="/Islemler/Yonlendir" method="post">
                                    <button type="submit" class="btn" asp-action="KullanicIslemleri" asp-controller="Home" style="background-color: #e65100; color: black;">Kullanıcı İşlemleri</button>
                                </form>
                            }
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - berber4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Bootstrap 5 Bundle (Bootstrap ve Popper.js) -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Kuafor_web/Views/Shared/_yönetimtema.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Paneli</title>
    <style>
        /* Genel Stil */
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            display: flex;
            background-color: #121212;
            color: #f1f1f1;
        }

        /* Sidebar */
        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #1e1e1e;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 20px 10px;
        }

            .sidebar h3 {
                color: #FF6600;
                text-align: center;
                font-size: 1.5em;
                margin-bottom: 30px;
            }

            .sidebar a {
                display: block;
                color: #f1f1f1;
                padding: 12px 20px;
                text-decoration: none;
                border-radius: 5px;
                margin-bottom: 10px;
                transition: background-color 0.3s ease, color 0.3s ease;
                font-weight: 500;
            }

                .sidebar a:hover {
                    background-color: #FF6600;
                    color: #121212;
                }

                .sidebar a.active {
                    background-color: #FF6600;
                    color: #121212;
                }

        /* Ana İçerik */
        .content {
            flex-grow: 1;
            padding: 20px;
        }

            .content h1 {
                color: #FF6600;
                font-size: 2em;
                margin-bottom: 20px;
            }

        /* Footer */
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #ddd;
        }
    </style>
</head>
<body>
    <!-- Sidebar -->
    <div class="sidebar">
        <div>
            <h3>Admin Paneli</h3>
            <a asp-controller="Home" asp-action="AnaSayfa" class="active">Anasayfa</a>
            <a asp-controller="Yonetim" asp-action="SalonGoster">Salonlar</a>
            <a asp-controller="Yonetim" asp-action="RandevuOnay">Randevular</a>
            <a asp-controller="Yonetim" asp-action="Kullanicilar">Tüm Kullanıcılar</a>
            <a asp-controller="Yonetim" asp-action="BerberGoster">Berberler</a>
            <a asp-controller="Home" asp-action="AnaSayfa">Anasayfa</a>
            <a asp-controller="Yonetim" asp-action="Bilgilerim">Bilgilerim</a>
        </div>
        <div>
            <a asp-controller="Giris" asp-action="CikisYap" style="color: #FF6666; font-weight: bold;">Çıkış Yap</a>
        </div>
    </div>

    <!-- Ana İçerik Alanı -->
    <div class="content">
        @RenderBody()
    </div>

    <!-- Footer -->
    <div class="footer">
    </div>
</body>
</html>